# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-19 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_apply',
            name='is_read',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0),
        ),
    ]
