# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-19 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_friend_apply_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend_apply',
            old_name='is_read',
            new_name='a_read',
        ),
        migrations.AddField(
            model_name='friend_apply',
            name='r_read',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0),
        ),
    ]
