# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_auto_20190419_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='g_delete',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='s_delete',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0),
        ),
    ]
