# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-19 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import lib.orm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Praise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('stime', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, lib.orm.ModelMixin),
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('message', models.TextField()),
                ('praise', models.IntegerField(default=0)),
                ('stime', models.DateTimeField(auto_now_add=True)),
                ('anonymous', models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0)),
            ],
            bases=(models.Model, lib.orm.ModelMixin),
        ),
    ]
